/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.ControllerCadastro;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author Gabriel
 */
public class JanelaCadastro extends javax.swing.JFrame {

    /**
     * Creates new form JanelaCadastro
     */
    public JanelaCadastro() {
        initComponents();
        control = new ControllerCadastro(this);
    }

    public ControllerCadastro getControl() {
        return control;
    }

    public void setControl(ControllerCadastro control) {
        this.control = control;
    }

    public JButton getBtCadastrar() {
        return btCadastrar;
    }

    public void setBtCadastrar(JButton btCadastrar) {
        this.btCadastrar = btCadastrar;
    }

    public JLabel getLblCadastro() {
        return lblCadastro;
    }

    public void setLblCadastro(JLabel lblCadastro) {
        this.lblCadastro = lblCadastro;
    }

    public JLabel getLblCpfC() {
        return lblCpfC;
    }

    public void setLblCpfC(JLabel lblCpfC) {
        this.lblCpfC = lblCpfC;
    }

    public JLabel getLblEntrar() {
        return lblEntrar;
    }

    public void setLblEntrar(JLabel lblEntrar) {
        this.lblEntrar = lblEntrar;
    }

    public JLabel getLblNomeC() {
        return lblNomeC;
    }

    public void setLblNomeC(JLabel lblNomeC) {
        this.lblNomeC = lblNomeC;
    }

    public JLabel getLblSenhaC() {
        return lblSenhaC;
    }

    public void setLblSenhaC(JLabel lblSenhaC) {
        this.lblSenhaC = lblSenhaC;
    }

    public JLabel getLblSenhaEntrar() {
        return lblSenhaEntrar;
    }

    public void setLblSenhaEntrar(JLabel lblSenhaEntrar) {
        this.lblSenhaEntrar = lblSenhaEntrar;
    }

    public JTextField getTxtCpfC() {
        return txtCpfC;
    }

    public void setTxtCpfC(JTextField txtCpfC) {
        this.txtCpfC = txtCpfC;
    }

    public JTextField getTxtNomeC() {
        return txtNomeC;
    }

    public void setTxtNomeC(JTextField txtNomeC) {
        this.txtNomeC = txtNomeC;
    }

    public JTextField getTxtSenhaC() {
        return txtSenhaC;
    }

    public void setTxtSenhaC(JTextField txtSenhaC) {
        this.txtSenhaC = txtSenhaC;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCadastro = new javax.swing.JLabel();
        lblCpfC = new javax.swing.JLabel();
        txtCpfC = new javax.swing.JTextField();
        lblSenhaC = new javax.swing.JLabel();
        txtSenhaC = new javax.swing.JTextField();
        btCadastrar = new javax.swing.JButton();
        lblEntrar = new javax.swing.JLabel();
        lblSenhaEntrar = new javax.swing.JLabel();
        lblNomeC = new javax.swing.JLabel();
        txtNomeC = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblCadastro.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCadastro.setText("Cadastro");

        lblCpfC.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCpfC.setText("Usuario:");

        txtCpfC.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtCpfC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCpfCActionPerformed(evt);
            }
        });

        lblSenhaC.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblSenhaC.setText("Senha:");

        txtSenhaC.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtSenhaC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSenhaCActionPerformed(evt);
            }
        });

        btCadastrar.setText("Cadastrar");
        btCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarActionPerformed(evt);
            }
        });

        lblEntrar.setText("Usuario com CPF");

        lblSenhaEntrar.setText("Senha com 6 digitos");

        lblNomeC.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNomeC.setText("Nome:");

        txtNomeC.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtNomeC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 58, Short.MAX_VALUE)
                .addComponent(lblCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(148, 148, 148)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblEntrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblSenhaEntrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(33, 33, 33))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNomeC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNomeC, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCpfC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCpfC, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(43, 43, 43)
                            .addComponent(lblSenhaC)
                            .addGap(18, 18, 18)
                            .addComponent(txtSenhaC, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(164, 164, 164)
                            .addComponent(btCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(lblCadastro))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(lblEntrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblSenhaEntrar)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomeC)
                    .addComponent(txtNomeC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCpfC)
                    .addComponent(txtCpfC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSenhaC)
                    .addComponent(txtSenhaC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67)
                .addComponent(btCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCpfCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCpfCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCpfCActionPerformed

    private void txtSenhaCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSenhaCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSenhaCActionPerformed

    private void btCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarActionPerformed
        control.salvaCadastro();
        new JanelaLogin().setVisible(true);
    }//GEN-LAST:event_btCadastrarActionPerformed

    private void txtNomeCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeCActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(JanelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(JanelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(JanelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(JanelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new JanelaCadastro().setVisible(true);
//            }
//        });
//    }
    private ControllerCadastro control;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCadastrar;
    private javax.swing.JLabel lblCadastro;
    private javax.swing.JLabel lblCpfC;
    private javax.swing.JLabel lblEntrar;
    private javax.swing.JLabel lblNomeC;
    private javax.swing.JLabel lblSenhaC;
    private javax.swing.JLabel lblSenhaEntrar;
    private javax.swing.JTextField txtCpfC;
    private javax.swing.JTextField txtNomeC;
    private javax.swing.JTextField txtSenhaC;
    // End of variables declaration//GEN-END:variables
}
