/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import DAO.Conexao;
import DAO.ContaDAO;
import javax.swing.JButton;
import javax.swing.JLabel;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.PreparedStatement;


/**
 *
 * @author Gabriel
 */
public class JanelaSaldo extends javax.swing.JFrame {
    private String cpf;
    /**
     * Creates new form JanelaSaldo
     */
    public JanelaSaldo(String cpf) {
        this.cpf = cpf;
        initComponents();
        exibirSaldo();
    }
    
    

    public String getCpf() {
        return cpf;
    }

    public void setCpf(String cpf) {
        this.cpf = cpf;
    }

    public JButton getBtSaldo() {
        return btSaldo;
    }

    public void setBtSaldo(JButton btSaldo) {
        this.btSaldo = btSaldo;
    }

    public JLabel getLblBtc() {
        return lblBtc;
    }

    public void setLblBtc(JLabel lblBtc) {
        this.lblBtc = lblBtc;
    }

    public JLabel getLblEth() {
        return lblEth;
    }

    public void setLblEth(JLabel lblEth) {
        this.lblEth = lblEth;
    }

    public JLabel getLblMostra() {
        return lblMostra;
    }

    public void setLblMostra(JLabel lblMostra) {
        this.lblMostra = lblMostra;
    }

    public JLabel getLblReal() {
        return lblReal;
    }

    public void setLblReal(JLabel lblReal) {
        this.lblReal = lblReal;
    }

    public JLabel getLblSaldo() {
        return lblSaldo;
    }

    public void setLblSaldo(JLabel lblSaldo) {
        this.lblSaldo = lblSaldo;
    }

    public JLabel getLblXrd() {
        return lblXrd;
    }

    public void setLblXrd(JLabel lblXrd) {
        this.lblXrd = lblXrd;
    }
    
        public void setSaldo(double saldo) {
        lblMostra.setText(String.valueOf(saldo));
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSaldo = new javax.swing.JLabel();
        btSaldo = new javax.swing.JButton();
        lblReal = new javax.swing.JLabel();
        lblBtc = new javax.swing.JLabel();
        lblEth = new javax.swing.JLabel();
        lblXrd = new javax.swing.JLabel();
        lblMostra = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblSaldo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblSaldo.setText("Seu saldo é:");

        btSaldo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btSaldo.setText("Voltar");
        btSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSaldoActionPerformed(evt);
            }
        });

        lblReal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblReal.setText("Reais:");

        lblBtc.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblBtc.setText("Bitcoin:");

        lblEth.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblEth.setText("Eth:");

        lblXrd.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblXrd.setText("Xrd:");

        lblMostra.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblMostra.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(btSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblReal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblMostra, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblSaldo)
                            .addComponent(lblBtc)
                            .addComponent(lblEth)
                            .addComponent(lblXrd))))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblSaldo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblReal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblMostra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBtc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblEth)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblXrd)
                .addGap(32, 32, 32)
                .addComponent(btSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSaldoActionPerformed
        new JanelaFuncoes(cpf).setVisible(true);
    }//GEN-LAST:event_btSaldoActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(JanelaSaldo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(JanelaSaldo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(JanelaSaldo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(JanelaSaldo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new JanelaSaldo().setVisible(true);
//            }
//        });
//    }
    private void exibirSaldo() {
        Conexao conexao = new Conexao();
        try {
            Connection conn = conexao.getConnection();
            String sql = "select saldo from usuarios where cpf = ?";
            try (PreparedStatement stmt = conn.prepareStatement(sql)) {
                stmt.setString(1, cpf);
                try (ResultSet rs = stmt.executeQuery()) {
                    if (rs.next()) {
                        double saldo = rs.getDouble("saldo");
                        lblMostra.setText(Double.toString(saldo));
                    } else {
                        lblMostra.setText("0.0"); // ou qualquer valor padrão
                    }
                }
            }
        } catch (SQLException ex) {
            // Trate ou registre a exceção adequadamente
            ex.printStackTrace();
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btSaldo;
    private javax.swing.JLabel lblBtc;
    private javax.swing.JLabel lblEth;
    private javax.swing.JLabel lblMostra;
    private javax.swing.JLabel lblReal;
    private javax.swing.JLabel lblSaldo;
    private javax.swing.JLabel lblXrd;
    // End of variables declaration//GEN-END:variables
}
