/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import DAO.Conexao;
import controller.ControllerCripto;
import javax.swing.JLabel;
import java.sql.SQLException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Connection;
import javax.swing.JOptionPane;
/**
 *
 * @author Gabriel
 */
public class JanelaCotacoes extends javax.swing.JFrame {
    private ControllerCripto controller;
 
    /**
     * Creates new form JanelaCotacoes
     */
    public JanelaCotacoes() {
        initComponents();
        controller = new ControllerCripto(this);
        atualizarCotacoes();
    }

    public ControllerCripto getController() {
        return controller;
    }

    public void setController(ControllerCripto controller) {
        this.controller = controller;
    }

    public JLabel getLblCotacoes() {
        return lblCotacoes;
    }

    public void setLblCotacoes(JLabel lblCotacoes) {
        this.lblCotacoes = lblCotacoes;
    }

    public JLabel getLblMostraBtc() {
        return lblMostraBtc;
    }

    public void setLblMostraBtc(JLabel lblMostraBtc) {
        this.lblMostraBtc = lblMostraBtc;
    }

    public JLabel getLblMostraEth() {
        return lblMostraEth;
    }

    public void setLblMostraEth(JLabel lblMostraEth) {
        this.lblMostraEth = lblMostraEth;
    }

    public JLabel getLblMostraXrp() {
        return lblMostraXrp;
    }

    public void setLblMostraXrp(JLabel lblMostraXrp) {
        this.lblMostraXrp = lblMostraXrp;
    }

    public JLabel getLblValorBtc() {
        return lblValorBtc;
    }

    public void setLblValorBtc(JLabel lblValorBtc) {
        this.lblValorBtc = lblValorBtc;
    }

    public JLabel getLblValorEth() {
        return lblValorEth;
    }

    public void setLblValorEth(JLabel lblValorEth) {
        this.lblValorEth = lblValorEth;
    }

    public JLabel getLblValorXrp() {
        return lblValorXrp;
    }

    public void setLblValorXrp(JLabel lblValorXrp) {
        this.lblValorXrp = lblValorXrp;
    }
//    private String recuperarCPFDaTabelaUsuarios() {
//    Conexao conexao = new Conexao();
//    String cpfUsuarioLogado = null;
//    try {
//        Connection conn = conexao.getConnection();
//        String sql = "SELECT cpf FROM usuarios WHERE cpf = ?"; // Substitua <condição_de_busca_do_cpf> pela sua condição de busca
//        try (PreparedStatement stmt = conn.prepareStatement(sql)) {
//            // Adicione parâmetros, se necessário
//            try (ResultSet rs = stmt.executeQuery()) {
//                if (rs.next()) {
//                    cpfUsuarioLogado = rs.getString("cpf");
//                }
//            }
//        }
//    } catch (SQLException ex) {
//        // Trate ou registre a exceção adequadamente
//        ex.printStackTrace();
//    }
//    return cpfUsuarioLogado;
//}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCotacoes = new javax.swing.JLabel();
        lblValorBtc = new javax.swing.JLabel();
        lblValorEth = new javax.swing.JLabel();
        lblValorXrp = new javax.swing.JLabel();
        lblMostraBtc = new javax.swing.JLabel();
        lblMostraEth = new javax.swing.JLabel();
        lblMostraXrp = new javax.swing.JLabel();
        btVoltar = new javax.swing.JButton();
        btAtualiza1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblCotacoes.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCotacoes.setText("Cotacoes das CriptoMoedas");

        lblValorBtc.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblValorBtc.setText("Btc:");

        lblValorEth.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblValorEth.setText("Eth:");

        lblValorXrp.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblValorXrp.setText("Xrp:");

        lblMostraBtc.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblMostraBtc.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblMostraEth.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblMostraEth.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblMostraXrp.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblMostraXrp.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btVoltar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btVoltar.setText("Voltar");
        btVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarActionPerformed(evt);
            }
        });

        btAtualiza1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btAtualiza1.setText("Atualizar");
        btAtualiza1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAtualiza1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(lblCotacoes)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblValorEth)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblMostraEth, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblValorBtc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblMostraBtc, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblValorXrp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblMostraXrp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(btVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(276, Short.MAX_VALUE)
                    .addComponent(btAtualiza1)
                    .addGap(28, 28, 28)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCotacoes)
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblValorBtc)
                            .addComponent(lblMostraBtc, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addComponent(lblValorEth))
                    .addComponent(lblMostraEth, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblValorXrp)
                    .addComponent(lblMostraXrp, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btVoltar))
                .addContainerGap(49, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(116, 116, 116)
                    .addComponent(btAtualiza1)
                    .addContainerGap(137, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btVoltarActionPerformed

    private void btAtualiza1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAtualiza1ActionPerformed
        controller.atualizarCotacoesAleatorias();atualizarCotacoes();
    }//GEN-LAST:event_btAtualiza1ActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(JanelaCotacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(JanelaCotacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(JanelaCotacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(JanelaCotacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new JanelaCotacoes().setVisible(true);
//            }
//        });
//    }
    private void atualizarCotacoes() {
        // Método para atualizar as cotações exibidas nas labels
        double btcCotacao = controller.getBtc().getCotacaoAtual();
        double ethCotacao = controller.getEth().getCotacaoAtual();
        double xrpCotacao = controller.getXrp().getCotacaoAtual();

        // Atualiza as labels com as novas cotações
        lblMostraBtc.setText(String.format("%.2f", btcCotacao));
        lblMostraEth.setText(String.format("%.2f", ethCotacao));
        lblMostraXrp.setText(String.format("%.2f", xrpCotacao));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAtualiza1;
    private javax.swing.JButton btVoltar;
    private javax.swing.JLabel lblCotacoes;
    private javax.swing.JLabel lblMostraBtc;
    private javax.swing.JLabel lblMostraEth;
    private javax.swing.JLabel lblMostraXrp;
    private javax.swing.JLabel lblValorBtc;
    private javax.swing.JLabel lblValorEth;
    private javax.swing.JLabel lblValorXrp;
    // End of variables declaration//GEN-END:variables
}
